// Shared data for all Mindray flow variations
window.MINDRAY_DATA = {
  title: "Fluxograma de Processos de Amostras",
  subtitle: "Automação Laboratorial Mindray — da recepção à liberação",

  stages: [
    {
      id: "S1",
      code: "01",
      name: "Origem das Amostras",
      short: "Origem",
      items: [
        { id: "amb", label: "Coleta ambulatorial", icon: "users" },
        { id: "hos", label: "Coleta hospitalar", icon: "hospital" },
        { id: "ext", label: "Coleta externa / domiciliar", icon: "home" },
        { id: "stat", label: "Urgência / STAT", icon: "urgent", flag: "stat" },
      ],
    },
    {
      id: "S2",
      code: "02",
      name: "Recepção Técnica",
      short: "Recepção",
      items: [
        { label: "Recepção técnica de amostras" },
        { label: "Conferência de cadastro" },
        { label: "Leitura de código de barras" },
        { label: "Recebimento por lote" },
        { label: "Priorização ROTINA / STAT" },
      ],
    },
    {
      id: "S3",
      code: "03",
      name: "Triagem Pré-analítica",
      short: "Triagem",
      items: [
        { label: "Identificação correta" },
        { label: "Volume suficiente" },
        { label: "Integridade da amostra" },
        { label: "Temperatura / transporte" },
        { label: "Verificação de hemólise / coágulo / lipemia" },
        { label: "Critérios de aceitação e rejeição" },
      ],
      decision: {
        question: "Amostra conforme?",
        yes: "Segue para automação",
        no: "Pendência / recoleta / rejeição",
      },
    },
    {
      id: "S4",
      code: "04",
      name: "Automação Pré-analítica",
      short: "Automação",
      instrument: "TM-1000 / MT 8000",
      items: [
        { label: "Bulk input" },
        { label: "Auto-registro" },
        { label: "Scan 360°" },
        { label: "Decapping automático" },
        { label: "Triagem inteligente" },
        { label: "Roteamento por setor" },
        { label: "Rastreamento RFID" },
        { label: "Prioridade para STAT", flag: "stat" },
        { label: "Armazenamento e sorting" },
      ],
      transport: "Esteira inteligente de transporte de tubos",
    },
  ],

  // Stage 5 — divisão por tipo de tubo
  tubes: [
    {
      id: "edta",
      code: "5A",
      tube: "EDTA roxo",
      color: "#7A4DBD",
      capColor: "#6B3FAD",
      sector: "Hematologia",
      instruments: [
        { name: "CAL 8000", note: "" },
        { name: "BC-6800Plus", note: "" },
        { name: "SC-120", note: "lâmina e coloração, quando necessário" },
        { name: "MC-80", note: "morfologia digital / reflexo" },
        { name: "H50 / HbA1c", note: "quando aplicável" },
      ],
      tests: ["CBC", "diferencial", "reticulócitos", "reflex / rerun / smear"],
      notes: "",
      tat: "20–40 min",
      tatMin: 20,
      tatMax: 40,
    },
    {
      id: "citrato",
      code: "5B",
      tube: "Citrato azul",
      color: "#2B6CB0",
      capColor: "#1E4E8C",
      sector: "Coagulação",
      pipeline: ["Centrifugação", "CX-9000"],
      tests: ["PT", "INR", "APTT", "fibrinogênio", "D-dímero"],
      notes: "Testes de coagulação e hemostasia",
      tat: "30–50 min",
      tatMin: 30,
      tatMax: 50,
    },
    {
      id: "soro",
      code: "5C",
      tube: "Soro/Gel · Heparina",
      tubeLong: "Soro / Gel amarelo-vermelho e Heparina verde",
      color: "#D69E2E",
      capColor: "#B07A1C",
      sector: "Bioquímica",
      pipeline: ["Centrifugação", "M1000 / MT 8000", "BS-2800M"],
      tests: ["química clínica", "eletrólitos", "índices séricos HIL"],
      notes: "",
      tat: "30–60 min",
      tatMin: 30,
      tatMax: 60,
    },
    {
      id: "plasma",
      code: "5D",
      tube: "Soro / Plasma",
      color: "#C53030",
      capColor: "#9B2424",
      sector: "Imunologia / Imunoensaio",
      pipeline: ["M1000 / linha integrada", "CL-8000i"],
      tests: ["hormônios", "marcadores", "sorologias", "imunoensaios"],
      notes: "",
      tat: "45–90 min",
      tatMin: 45,
      tatMax: 90,
    },
    {
      id: "fluoreto",
      code: "5E",
      tube: "Fluoreto cinza",
      color: "#718096",
      capColor: "#4A5568",
      sector: "Metabólitos especiais",
      pipeline: ["Triagem", "Bioquímica", "dosagem de glicose / lactato"],
      tests: [],
      notes: "Amostras especiais; estabilidade e temperatura",
      tat: "30–60 min",
      tatMin: 30,
      tatMax: 60,
    },
    {
      id: "urina",
      code: "5F",
      tube: "Urina",
      color: "#D4A017",
      capColor: "#A87E10",
      sector: "Uroanálise",
      pipeline: [
        "Recepção específica",
        "Triagem",
        "Análise físico-química",
        "Microscopia / sedimento (quando necessário)",
      ],
      tests: [],
      notes: "Sedimento, cristais, células, cilindros",
      tat: "20–40 min",
      tatMin: 20,
      tatMax: 40,
    },
    {
      id: "micro",
      code: "5G",
      tube: "Hemocultura · Microbiologia",
      tubeLong: "Frascos de hemocultura e amostras microbiológicas",
      color: "#2F855A",
      capColor: "#1F5F3F",
      sector: "Microbiologia",
      pipeline: [
        "Recepção específica",
        "FA-N Series",
        "Monitoramento da positividade",
        "Alerta de positivo",
        "Gram / subcultura / identificação e sensibilidade",
        "Laudo parcial e final",
      ],
      tests: ["hemocultura", "ID/AST"],
      notes: "Tempo dependente do crescimento",
      tat: "Alerta em horas · laudo 24–72 h+",
      tatMin: 240,
      tatMax: 4320,
    },
  ],

  middleware: {
    name: "Middleware / labXpert / LIS",
    features: [
      { label: "Autoverificação", icon: "check" },
      { label: "Delta check", icon: "trend" },
      { label: "Reflex test", icon: "branch" },
      { label: "Rerun", icon: "refresh" },
      { label: "Consolidação por paciente", icon: "user" },
      { label: "Monitoramento de TAT", icon: "gauge" },
      { label: "Painel operacional", icon: "panel" },
    ],
  },

  postAnalytic: [
    { label: "Validação técnica", icon: "magnifier" },
    { label: "Validação biomédica / farmacêutica / médica", icon: "doctor" },
    { label: "Liberação do laudo", icon: "doc-check" },
    { label: "Entrega digital / impresso / integração hospitalar", icon: "cloud" },
    { label: "Soroteca / armazenamento refrigerado", icon: "fridge" },
    { label: "Descarte conforme POP", icon: "biohazard" },
  ],

  specialRules: [
    { label: "STAT com prioridade na esteira", icon: "timer" },
    { label: "Amostras com HIL ou coágulo seguem para exceção", icon: "alert-tube" },
    { label: "Reflexo automático em hematologia", icon: "microscope" },
    { label: "Recolheita quando amostra inadequada", icon: "redo" },
    { label: "Rastreabilidade ponta a ponta", icon: "barcode" },
  ],

  benefits: [
    "Redução de erros pré-analíticos",
    "Maior produtividade",
    "Menor TAT",
    "Melhor rastreabilidade",
    "Segurança biológica",
    "Padronização do fluxo",
  ],
};

// === GENOMA LAB FLOOR PLAN — physical rooms and equipment ===
// Coords in a 1280×960 viewBox. Each room is a rectangle with metadata.
window.GENOMA = {
  building: {
    title: "Unidade de Processamento — Laboratório Genoma",
    subtitle: "Planta baixa — área de processamento",
    totalArea: 263.20,
  },

  // Entry point — collaborator emerges from ACESSO ESCADAS into upper corridor
  entry: { x: 540, y: 200, label: "Saída do ACESSO ESCADAS · chegada do colaborador" },

  // Staircase inside ACESSO ESCADAS (drawn as visual element inside the room)
  stairs: { x: 480, y: 50, w: 220, h: 130, steps: 12 },

  // Collaborator path — yellow flow from stair landing into TRIAGEM
  collaboratorPath: ["entryBelow", "entry", "circTop", "triagemDoor"],

  rooms: [
    { id: "ester", name: "ESTERILIZAÇÃO", area: 8.27, x: 130, y: 30, w: 200, h: 120,
      kind: "support", door: { side: "bottom", at: 0.5 },
      stages: ["S7-ster"],
      mindrayMap: "Esterilização de bancadas e suprimentos · suporte ao Estágio 07 (descarte conforme POP)",
      equipment: [
        { type: "sink", x: 140, y: 60, w: 50, h: 40, label: "pia" },
        { type: "autoclave", x: 230, y: 60, w: 60, h: 50, label: "autoclave" },
      ],
    },
    { id: "acesso", name: "ACESSO ESCADAS", area: 20.91, x: 360, y: 30, w: 400, h: 175,
      kind: "circulation-major", door: { side: "bottom", at: 0.35 },
      stages: [],
      mindrayMap: "Acesso vertical à área de processamento · ponto de entrada do colaborador com amostras (uso compartilhado).",
      equipment: [
        { type: "stairs", x: 380, y: 50, w: 220, h: 130, label: "escada · sobe", steps: 12 },
        { type: "rail", x: 620, y: 50, w: 130, h: 130, label: "guarda-corpo" },
      ],
    },
    { id: "triagem", name: "TRIAGEM", area: 11.16, x: 130, y: 170, w: 170, h: 190,
      door: { side: "right", at: 0.7 },
      stages: ["S2", "S3"],
      mindrayMap: "Estágios 02 + 03 · Recepção técnica e triagem pré-analítica · ponto único de entrada na cadeia de custódia",
      equipment: [
        { type: "bench", x: 140, y: 180, w: 150, h: 25, label: "bancada cadastro" },
        { type: "workstation", x: 150, y: 210, w: 55, h: 50, label: "PC + leitor cód. barras" },
        { type: "workstation", x: 215, y: 210, w: 55, h: 50, label: "PC + leitor cód. barras" },
        { type: "sink", x: 200, y: 270, w: 40, h: 35, label: "pia" },
        { type: "fridge", x: 145, y: 320, w: 32, h: 35, label: "câm. amostras" },
        { type: "fridge", x: 185, y: 320, w: 32, h: 35, label: "câm. amostras" },
      ],
    },
    { id: "circTop", name: "CIRCULAÇÃO", area: 9.06, x: 300, y: 210, w: 240, h: 150,
      kind: "corridor", stages: [],
    },
    { id: "uro", name: "UROANÁLISE / PARASIT.", area: 14.96, x: 540, y: 210, w: 340, h: 150,
      door: { side: "left", at: 0.5 },
      stages: ["S5F"], tubes: ["urina", "fluoreto"],
      mindrayMap: "Estágio 05F · Uroanálise + Parasitologia · 3 estações de trabalho · microscopia e físico-química",
      equipment: [
        { type: "workstation", x: 560, y: 220, w: 55, h: 55, label: "estação 1" },
        { type: "workstation", x: 640, y: 220, w: 55, h: 55, label: "estação 2 (analisador)" },
        { type: "workstation", x: 730, y: 220, w: 55, h: 55, label: "estação 3 (microscopia)" },
        { type: "bench", x: 560, y: 290, w: 290, h: 60, label: "bancada técnica" },
      ],
    },
    { id: "descarte", name: "DESCARTE", area: 1.57, x: 1010, y: 150, w: 110, h: 70,
      kind: "support", stages: ["S7-desc"],
      mindrayMap: "Descarte conforme POP · Estágio 07 terminal · acessível pelo corredor",
      equipment: [
        { type: "biohazard", x: 1020, y: 165, w: 30, h: 40, label: "lixo bio" },
        { type: "sink", x: 1065, y: 165, w: 40, h: 40, label: "pia" },
      ],
    },
    { id: "centrif", name: "CENTRIF.", area: 5.49, x: 1010, y: 220, w: 140, h: 140,
      door: { side: "left", at: 0.5 },
      stages: ["S5B-prep", "S5C-prep", "S5D-prep"], tubes: ["citrato", "soro", "plasma", "fluoreto"],
      mindrayMap: "Centrifugação pré-analítica para soro/plasma/coagulação · gargalo para 4 de 7 rotas (B/C/D/E)",
      equipment: [
        { type: "workstation", x: 1015, y: 230, w: 55, h: 50, label: "PC" },
        { type: "centrifuge", x: 1080, y: 235, w: 50, h: 50, label: "centrífuga 1" },
        { type: "centrifuge", x: 1080, y: 295, w: 50, h: 50, label: "centrífuga 2" },
      ],
    },
    { id: "extr", name: "EXTRAÇÃO", area: 7.70, x: 130, y: 370, w: 210, h: 120,
      door: { side: "right", at: 0.5 },
      stages: ["S-mol-prep"], extra: "molecular",
      mindrayMap: "Extração de ácido nucleico · sala isolada para evitar contaminação · workflow molecular",
      equipment: [
        { type: "bench", x: 140, y: 380, w: 190, h: 25, label: "bancada extração" },
        { type: "workstation", x: 170, y: 415, w: 55, h: 55, label: "estação extração DNA/RNA" },
        { type: "pipette", x: 240, y: 425, w: 25, h: 40, label: "kit pipetas" },
      ],
    },
    { id: "amp", name: "AMPLIFICAÇÃO", area: 7.70, x: 130, y: 510, w: 210, h: 110,
      door: { side: "right", at: 0.5 },
      stages: ["S-mol-pcr"], extra: "molecular",
      mindrayMap: "Sala dedicada à amplificação por PCR/qPCR · separada da extração para evitar contaminação cruzada · contém analisador Coagulação C3510",
      equipment: [
        { type: "bench", x: 140, y: 520, w: 190, h: 22, label: "bancada PCR" },
        { type: "workstation", x: 145, y: 552, w: 70, h: 55, label: "PC + termociclador" },
        { type: "coagAnalyzer", x: 230, y: 552, w: 95, h: 55, label: "Coagulação C3510" },
      ],
    },
    { id: "laudos", name: "LAUDOS", area: 5.60, x: 130, y: 640, w: 210, h: 130,
      door: { side: "right", at: 0.6 },
      stages: ["S6", "S7"],
      mindrayMap: "Estágios 06 + 07 · Validação técnica + biomédica + liberação do laudo · ponto único de saída do fluxo",
      equipment: [
        { type: "workstation", x: 155, y: 660, w: 55, h: 55, label: "PC validação" },
        { type: "workstation", x: 230, y: 660, w: 55, h: 55, label: "PC liberação" },
        { type: "bench", x: 140, y: 730, w: 190, h: 25, label: "bancada laudos" },
      ],
    },
    { id: "micro", name: "MICROBIOLOGIA", area: 32.52, x: 480, y: 370, w: 400, h: 280,
      door: { side: "top", at: 0.15 },
      stages: ["S5G"], tubes: ["micro"],
      mindrayMap: "Estágio 05G · Hemocultura + cultura geral · Phoenix M50 (BD), UN Virtek 2 (×2 ID + antibiograma), Vitek MS Prime (MALDI-TOF) · TAT alerta horas / final 24-72 h",
      equipment: [
        { type: "sink", x: 495, y: 385, w: 45, h: 35, label: "pia" },
        { type: "bench", x: 555, y: 385, w: 60, h: 35, label: "bancada" },
        { type: "bench", x: 625, y: 385, w: 60, h: 35, label: "bancada" },
        // Left column — incubators (4 stacked)
        { type: "incubator", x: 495, y: 430, w: 55, h: 50, label: "incubadora 1" },
        { type: "incubator", x: 495, y: 485, w: 55, h: 50, label: "incubadora 2" },
        { type: "incubator", x: 495, y: 540, w: 55, h: 50, label: "incubadora 3" },
        { type: "incubator", x: 495, y: 595, w: 55, h: 50, label: "incubadora 4" },
        // Phoenix M50 in center-back
        { type: "phoenix", x: 580, y: 440, w: 130, h: 70, label: "Phoenix M50 (BD)" },
        // Bottom row — Virtek and Vitek
        { type: "virtek", x: 580, y: 530, w: 75, h: 110, label: "UN Virtek 2" },
        { type: "virtek", x: 665, y: 530, w: 75, h: 110, label: "UN Virtek 2" },
        { type: "vitek", x: 750, y: 530, w: 110, h: 110, label: "Vitek MS Prime" },
        // Right side — microscope + workstation
        { type: "microscope", x: 780, y: 430, w: 40, h: 55, label: "microscópio binocular" },
        { type: "workstation", x: 720, y: 440, w: 50, h: 50, label: "PC ID/AST" },
      ],
    },
    { id: "circBot", name: "CIRCULAÇÃO", area: 17.67, x: 370, y: 670, w: 510, h: 100,
      kind: "corridor", stages: [],
    },
    { id: "elev", name: "ELEVADOR", area: 2.88, x: 1010, y: 420, w: 110, h: 90,
      kind: "utility", stages: [],
      mindrayMap: "Acesso vertical · transporte de suprimentos e amostras entre andares",
    },
    { id: "lab", name: "LABORATÓRIOS", area: 102.50, x: 370, y: 780, w: 780, h: 160,
      stages: ["S5A", "S5B", "S5C", "S5D", "S5E"], tubes: ["edta", "citrato", "soro", "plasma", "fluoreto"],
      mindrayMap: "Estágio 05 (A-E) · Hematologia (CAL 6000) · Bioquímica (BS 2000 ×2) · Imunoensaio · EQUIPAMENTO N° 01 · 4 estações de leitura · sala ampla com mais de 100 m²",
      equipment: [
        // Top bench analyzers
        { type: "bs2000Bench", x: 540, y: 790, w: 130, h: 28, label: "BS 2000" },
        { type: "cal6000Bench", x: 700, y: 790, w: 130, h: 28, label: "CAL 6000" },
        // Left column — large BS 2000 + Samsung fridge + eyewash
        { type: "bs2000Floor", x: 385, y: 800, w: 90, h: 90, label: "BS 2000" },
        { type: "samsungFridge", x: 385, y: 870, w: 90, h: 60, label: "Geladeira Duplex 435L Samsung" },
        { type: "eyewash", x: 385, y: 935, w: 30, h: 22, label: "Chuveiro lava-olhos" },
        // 4 workstations in 2 rows
        { type: "workstation", x: 555, y: 850, w: 65, h: 55, label: "estação 1" },
        { type: "workstation", x: 635, y: 850, w: 65, h: 55, label: "estação 2" },
        { type: "workstation", x: 715, y: 850, w: 65, h: 55, label: "estação 3" },
        { type: "workstation", x: 795, y: 850, w: 65, h: 55, label: "estação 4" },
        // Equipamento N° 01 on right
        { type: "equipNum01", x: 1000, y: 795, w: 140, h: 140, label: "EQUIPAMENTO N° 01" },
      ],
    },
  ],

  // Sample routes — each tube type's physical path through the rooms
  // (Collaborator delivers at triagem; sample flow starts from triagem onward)
  routes: {
    edta: { color: "#7A4DBD", code: "5A", name: "EDTA · Hematologia",
      path: ["triagemDoor", "circTop", "circBot", "lab", "circBot", "laudos"],
      via: ["lab"], steps: [
        "Colaborador entrega tubo em TRIAGEM",
        "Cadastro e triagem pré-analítica",
        "Corredor central",
        "Hematologia em LABORATÓRIOS (CAL 6000 + analisadores)",
        "Validação e liberação em LAUDOS",
      ],
    },
    citrato: { color: "#2B6CB0", code: "5B", name: "Citrato · Coagulação",
      path: ["triagemDoor", "circTop", "centrif", "circTop", "circBot", "lab", "laudos"],
      via: ["centrif", "lab"], steps: [
        "Colaborador entrega tubo em TRIAGEM", "Cadastro pré-analítico",
        "Centrifugação em CENTRIF.",
        "Analisador de coagulação em LABORATÓRIOS",
        "Liberação em LAUDOS",
      ],
    },
    soro: { color: "#D69E2E", code: "5C", name: "Soro / Heparina · Bioquímica",
      path: ["triagemDoor", "circTop", "centrif", "circTop", "circBot", "lab", "laudos"],
      via: ["centrif", "lab"], steps: [
        "Colaborador entrega tubo em TRIAGEM", "Cadastro pré-analítico",
        "Centrifugação em CENTRIF.",
        "Bioquímica BS 2000 em LABORATÓRIOS",
        "Liberação em LAUDOS",
      ],
    },
    plasma: { color: "#C53030", code: "5D", name: "Plasma · Imunologia",
      path: ["triagemDoor", "circTop", "centrif", "circTop", "circBot", "lab", "laudos"],
      via: ["centrif", "lab"], steps: [
        "Colaborador entrega tubo em TRIAGEM", "Cadastro pré-analítico",
        "Centrifugação em CENTRIF.",
        "Imunoensaio em LABORATÓRIOS",
        "Liberação em LAUDOS",
      ],
    },
    fluoreto: { color: "#718096", code: "5E", name: "Fluoreto · Metabólitos",
      path: ["triagemDoor", "circTop", "centrif", "circTop", "circBot", "lab", "laudos"],
      via: ["centrif", "lab"], steps: [
        "Colaborador entrega tubo em TRIAGEM", "Cadastro pré-analítico",
        "Centrifugação rápida em CENTRIF.",
        "Bioquímica em LABORATÓRIOS",
        "Liberação em LAUDOS",
      ],
    },
    urina: { color: "#D4A017", code: "5F", name: "Urina · Uroanálise",
      path: ["triagemDoor", "circTop", "uro", "circTop", "circBot", "laudos"],
      via: ["uro"], steps: [
        "Colaborador entrega frasco em TRIAGEM", "Cadastro pré-analítico",
        "Uroanálise / Parasitologia",
        "Liberação em LAUDOS",
      ],
    },
    micro: { color: "#2F855A", code: "5G", name: "Hemocultura · Microbiologia",
      path: ["triagemDoor", "circTop", "circBot", "micro", "circBot", "laudos"],
      via: ["micro"], steps: [
        "Colaborador entrega frasco em TRIAGEM", "Cadastro pré-analítico",
        "Incubação/cultura em MICROBIOLOGIA",
        "Alerta + ID/AST",
        "Laudo parcial e final em LAUDOS",
      ],
    },
    molecular: { color: "#B48CFF", code: "5H", name: "Molecular · PCR",
      path: ["triagemDoor", "circTop", "circBot", "extr", "amp", "lab", "laudos"],
      via: ["extr", "amp"], steps: [
        "Colaborador entrega tubo em TRIAGEM", "Cadastro pré-analítico",
        "Extração de ácido nucleico em EXTRAÇÃO",
        "Amplificação por PCR em AMPLIFICAÇÃO (sala dedicada)",
        "Leitura/análise em LABORATÓRIOS ou Equipamento I.A.",
        "Liberação em LAUDOS",
      ],
    },
  },
};

